insert into public.technical_questions (season_id, kind, slot, position, key, prompt, sort_order, active)
select
  s.id,
  v.kind::text,
  v.slot::int,
  v.position::text,
  v.key::text,
  v.prompt::text,
  v.sort_order::int,
  v.active::boolean
from public.seasons s
cross join (
  values
    ('base', 1, null, 'daily_base_intensidade', 'Intensidade e energia no treino', 10, true),
    ('base', 1, null, 'daily_base_atencao', 'Atenção e concentração', 20, true),
    ('base', 1, null, 'daily_base_esforco_defensivo', 'Esforço defensivo (sem bola)', 30, true),
    ('base', 1, null, 'daily_base_tomada_decisao', 'Tomada de decisão', 40, true),
    ('base', 1, null, 'daily_base_execucao_fundamentos', 'Execução dos fundamentos', 50, true),
    ('base', 1, null, 'daily_base_comunicacao', 'Comunicação e liderança', 60, true),
    ('base', 1, null, 'daily_base_disciplina_tatica', 'Disciplina tática (entender e cumprir função)', 70, true),
    ('base', 1, null, 'daily_base_resiliencia', 'Resiliência após erro', 80, true),

    ('position', 2, 'goleiro', 'daily_goleiro_s2_reposicao', 'Reposição (mãos/pés) e início de jogo', 10, true),
    ('position', 2, 'goleiro', 'daily_goleiro_s2_reflexo', 'Reflexo e tempo de reação', 20, true),
    ('position', 2, 'goleiro', 'daily_goleiro_s2_jogo_aereo', 'Jogo aéreo (saídas e bolas altas)', 30, true),
    ('position', 2, 'goleiro', 'daily_goleiro_s2_posicionamento', 'Posicionamento no gol', 40, true),
    ('position', 2, 'goleiro', 'daily_goleiro_s2_1x1', 'Situações de 1x1', 50, true),
    ('position', 2, 'goleiro', 'daily_goleiro_s2_bola_com_pes', 'Bola com os pés sob pressão', 60, true),

    ('position', 3, 'goleiro', 'daily_goleiro_s3_comando_area', 'Comando de área e comunicação', 10, true),
    ('position', 3, 'goleiro', 'daily_goleiro_s3_decisao_saida', 'Decisão de sair ou permanecer', 20, true),
    ('position', 3, 'goleiro', 'daily_goleiro_s3_organizacao_defesa', 'Organização da linha defensiva', 30, true),
    ('position', 3, 'goleiro', 'daily_goleiro_s3_recuperacao_erro', 'Recuperação após falha', 40, true),
    ('position', 3, 'goleiro', 'daily_goleiro_s3_leitura_jogo', 'Leitura de jogo e antecipação', 50, true),
    ('position', 3, 'goleiro', 'daily_goleiro_s3_coragem', 'Coragem e presença (impacto psicológico)', 60, true),

    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_marcacao_1x1', 'Marcação 1x1 e tempo de bote', 10, true),
    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_jogo_aereo', 'Jogo aéreo (defesa)', 20, true),
    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_cobertura', 'Cobertura e proteção da área', 30, true),
    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_saida_bola', 'Saída de bola (passe/lançamento)', 40, true),
    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_antecipacao', 'Antecipação e leitura de interceptação', 50, true),
    ('position', 2, 'zagueiro', 'daily_zagueiro_s2_controle_pressao', 'Controle sob pressão', 60, true),

    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_linha_defensiva', 'Sincronização da linha defensiva', 10, true),
    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_comunicacao', 'Comunicação e liderança defensiva', 20, true),
    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_transicao_def', 'Transição defensiva (reação pós-perda)', 30, true),
    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_temperamento', 'Temperamento e controle emocional', 40, true),
    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_faltas', 'Uso inteligente de faltas (sem excesso)', 50, true),
    ('position', 3, 'zagueiro', 'daily_zagueiro_s3_duelos', 'Intensidade nos duelos', 60, true),

    ('position', 2, 'lateral', 'daily_lateral_s2_apoio', 'Apoio ofensivo e amplitude', 10, true),
    ('position', 2, 'lateral', 'daily_lateral_s2_cruzamento', 'Cruzamento/passe final na faixa', 20, true),
    ('position', 2, 'lateral', 'daily_lateral_s2_1x1_def', '1x1 defensivo (acompanhar e desarmar)', 30, true),
    ('position', 2, 'lateral', 'daily_lateral_s2_transicao', 'Transição (subir e recompor)', 40, true),
    ('position', 2, 'lateral', 'daily_lateral_s2_dominio_passe', 'Domínio e passe em velocidade', 50, true),
    ('position', 2, 'lateral', 'daily_lateral_s2_pressao', 'Pressão no portador (timing)', 60, true),

    ('position', 3, 'lateral', 'daily_lateral_s3_tatica', 'Entender momento de subir/segurar', 10, true),
    ('position', 3, 'lateral', 'daily_lateral_s3_cobertura', 'Cobertura interna e proteção do corredor', 20, true),
    ('position', 3, 'lateral', 'daily_lateral_s3_leitura', 'Leitura de jogo (interceptações)', 30, true),
    ('position', 3, 'lateral', 'daily_lateral_s3_intensidade', 'Intensidade e repetição de sprints', 40, true),
    ('position', 3, 'lateral', 'daily_lateral_s3_concentracao', 'Concentração em trocas de marcação', 50, true),
    ('position', 3, 'lateral', 'daily_lateral_s3_duelos', 'Duelos no corredor', 60, true),

    ('position', 2, 'volante', 'daily_volante_s2_saida_bola', 'Saída de bola (passe curto/virada)', 10, true),
    ('position', 2, 'volante', 'daily_volante_s2_protecao', 'Proteção da frente da zaga', 20, true),
    ('position', 2, 'volante', 'daily_volante_s2_desarme', 'Desarme e recuperação de bola', 30, true),
    ('position', 2, 'volante', 'daily_volante_s2_marcar_linhas', 'Marcar linhas e fechar espaços', 40, true),
    ('position', 2, 'volante', 'daily_volante_s2_cobertura', 'Coberturas e dobras', 50, true),
    ('position', 2, 'volante', 'daily_volante_s2_pressao', 'Pressão e reação à perda', 60, true),

    ('position', 3, 'volante', 'daily_volante_s3_posicionamento', 'Posicionamento e leitura de jogo', 10, true),
    ('position', 3, 'volante', 'daily_volante_s3_organizacao', 'Organização do meio-campo', 20, true),
    ('position', 3, 'volante', 'daily_volante_s3_tomada', 'Tomada de decisão sob pressão', 30, true),
    ('position', 3, 'volante', 'daily_volante_s3_transicao', 'Transição (ganha/perde)', 40, true),
    ('position', 3, 'volante', 'daily_volante_s3_comunicacao', 'Comunicação e liderança', 50, true),
    ('position', 3, 'volante', 'daily_volante_s3_duelos', 'Duelos e intensidade', 60, true),

    ('position', 2, 'meia', 'daily_meia_s2_criacao', 'Criação (último passe e visão)', 10, true),
    ('position', 2, 'meia', 'daily_meia_s2_controle_orientado', 'Controle orientado e giro', 20, true),
    ('position', 2, 'meia', 'daily_meia_s2_passe_curto', 'Passe curto sob pressão', 30, true),
    ('position', 2, 'meia', 'daily_meia_s2_chute', 'Finalização de média distância', 40, true),
    ('position', 2, 'meia', 'daily_meia_s2_drible', 'Drible e condução em espaço curto', 50, true),
    ('position', 2, 'meia', 'daily_meia_s2_entre_linhas', 'Movimento entre linhas', 60, true),

    ('position', 3, 'meia', 'daily_meia_s3_decisao', 'Decisão (quando acelerar ou pausar)', 10, true),
    ('position', 3, 'meia', 'daily_meia_s3_pressao', 'Pressão pós-perda (primeira pressão)', 20, true),
    ('position', 3, 'meia', 'daily_meia_s3_compactacao', 'Compactação e recomposição', 30, true),
    ('position', 3, 'meia', 'daily_meia_s3_temperamento', 'Controle emocional e constância', 40, true),
    ('position', 3, 'meia', 'daily_meia_s3_comunicacao', 'Comunicação e liderança', 50, true),
    ('position', 3, 'meia', 'daily_meia_s3_leitura', 'Leitura do jogo (linhas de passe)', 60, true),

    ('position', 2, 'ponta', 'daily_ponta_s2_1x1', '1x1 ofensivo (drible e quebra)', 10, true),
    ('position', 2, 'ponta', 'daily_ponta_s2_finalizacao', 'Finalização (corte para dentro ou linha)', 20, true),
    ('position', 2, 'ponta', 'daily_ponta_s2_cruzamento', 'Cruzamento e passe final', 30, true),
    ('position', 2, 'ponta', 'daily_ponta_s2_velocidade', 'Velocidade com bola', 40, true),
    ('position', 2, 'ponta', 'daily_ponta_s2_movimento', 'Movimento de profundidade', 50, true),
    ('position', 2, 'ponta', 'daily_ponta_s2_dominio', 'Domínio e condução na linha', 60, true),

    ('position', 3, 'ponta', 'daily_ponta_s3_pressao', 'Pressão e recomposição no corredor', 10, true),
    ('position', 3, 'ponta', 'daily_ponta_s3_decisao', 'Decisão (quando driblar ou soltar)', 20, true),
    ('position', 3, 'ponta', 'daily_ponta_s3_sem_bola', 'Movimento sem bola (apoio e ruptura)', 30, true),
    ('position', 3, 'ponta', 'daily_ponta_s3_concentracao', 'Concentração e consistência', 40, true),
    ('position', 3, 'ponta', 'daily_ponta_s3_duelos', 'Duelos e intensidade', 50, true),
    ('position', 3, 'ponta', 'daily_ponta_s3_coragem', 'Coragem para jogar e assumir risco', 60, true),

    ('position', 2, 'atacante', 'daily_atacante_s2_finalizacao', 'Finalização (qualidade e escolha)', 10, true),
    ('position', 2, 'atacante', 'daily_atacante_s2_movimento', 'Movimento na área (desmarque)', 20, true),
    ('position', 2, 'atacante', 'daily_atacante_s2_apoio', 'Apoio (pivô e parede)', 30, true),
    ('position', 2, 'atacante', 'daily_atacante_s2_1x1', '1x1 em zona de finalização', 40, true),
    ('position', 2, 'atacante', 'daily_atacante_s2_profundidade', 'Ataque à profundidade', 50, true),
    ('position', 2, 'atacante', 'daily_atacante_s2_pressao', 'Pressão na saída adversária', 60, true),

    ('position', 3, 'atacante', 'daily_atacante_s3_decisao', 'Decisão no último terço', 10, true),
    ('position', 3, 'atacante', 'daily_atacante_s3_movimento_sem_bola', 'Movimento sem bola e leitura de cruzamentos', 20, true),
    ('position', 3, 'atacante', 'daily_atacante_s3_compromisso', 'Compromisso defensivo (pressing)', 30, true),
    ('position', 3, 'atacante', 'daily_atacante_s3_coragem', 'Coragem para finalizar e assumir risco', 40, true),
    ('position', 3, 'atacante', 'daily_atacante_s3_temperamento', 'Controle emocional em chances perdidas', 50, true),
    ('position', 3, 'atacante', 'daily_atacante_s3_duelos', 'Duelos e proteção de bola', 60, true)
) as v(kind, slot, position, key, prompt, sort_order, active)
where s.is_active = true
on conflict (season_id, kind, slot, position, key) do nothing;

insert into public.technical_monthly_questions (season_id, kind, position, key, prompt, sort_order, active)
select
  s.id,
  v.kind::text,
  v.position::text,
  v.key::text,
  v.prompt::text,
  v.sort_order::int,
  v.active::boolean
from public.seasons s
cross join (
  values
    ('base', null, 'monthly_base_passe', 'Passe (qualidade e escolha)', 10, true),
    ('base', null, 'monthly_base_primeiro_toque', 'Primeiro toque e controle orientado', 20, true),
    ('base', null, 'monthly_base_conducao', 'Condução e domínio em velocidade', 30, true),
    ('base', null, 'monthly_base_drible', 'Drible (eficácia e risco)', 40, true),
    ('base', null, 'monthly_base_finalizacao', 'Finalização (técnica e decisão)', 50, true),
    ('base', null, 'monthly_base_visao', 'Visão de jogo e leitura de opções', 60, true),
    ('base', null, 'monthly_base_tomada_decisao', 'Tomada de decisão sob pressão', 70, true),
    ('base', null, 'monthly_base_inteligencia_tatica', 'Inteligência tática', 80, true),
    ('base', null, 'monthly_base_posicionamento', 'Posicionamento (com/sem bola)', 90, true),
    ('base', null, 'monthly_base_compactacao', 'Compactação e recomposição', 100, true),
    ('base', null, 'monthly_base_pressao', 'Pressão pós-perda e intensidade defensiva', 110, true),
    ('base', null, 'monthly_base_duelos', 'Duelos físicos e proteção de bola', 120, true),
    ('base', null, 'monthly_base_resistencia', 'Resistência e repetição de ações', 130, true),
    ('base', null, 'monthly_base_velocidade', 'Velocidade e aceleração', 140, true),
    ('base', null, 'monthly_base_forca', 'Força e equilíbrio', 150, true),
    ('base', null, 'monthly_base_disciplina', 'Disciplina e cumprir orientações', 160, true),
    ('base', null, 'monthly_base_concentracao', 'Concentração e regularidade', 170, true),
    ('base', null, 'monthly_base_coragem', 'Coragem para jogar e assumir responsabilidade', 180, true),
    ('base', null, 'monthly_base_resiliencia', 'Resiliência (após erro/pressão)', 190, true),
    ('base', null, 'monthly_base_lideranca', 'Liderança e comunicação', 200, true),
    ('base', null, 'monthly_base_trabalho_em_equipe', 'Trabalho em equipe e cooperação', 210, true),
    ('base', null, 'monthly_base_aprendizado', 'Evolução e capacidade de aprender', 220, true),
    ('base', null, 'monthly_base_constancia', 'Constância no mês (performance média)', 230, true),
    ('base', null, 'monthly_base_competitividade', 'Competitividade e mentalidade', 240, true),

    ('position', 'goleiro', 'monthly_goleiro_reflexo', 'Reflexo e tempo de reação', 10, true),
    ('position', 'goleiro', 'monthly_goleiro_posicionamento', 'Posicionamento e ângulos', 20, true),
    ('position', 'goleiro', 'monthly_goleiro_jogo_aereo', 'Jogo aéreo e saídas', 30, true),
    ('position', 'goleiro', 'monthly_goleiro_1x1', '1x1 (tempo e coragem)', 40, true),
    ('position', 'goleiro', 'monthly_goleiro_reposicao', 'Reposição e início de jogo', 50, true),
    ('position', 'goleiro', 'monthly_goleiro_bola_com_pes', 'Bola com os pés sob pressão', 60, true),
    ('position', 'goleiro', 'monthly_goleiro_comando_area', 'Comando de área e comunicação', 70, true),
    ('position', 'goleiro', 'monthly_goleiro_leitura', 'Leitura e antecipação', 80, true),
    ('position', 'goleiro', 'monthly_goleiro_regularidade', 'Regularidade e controle emocional', 90, true),
    ('position', 'goleiro', 'monthly_goleiro_organizacao', 'Organização da defesa', 100, true),
    ('position', 'goleiro', 'monthly_goleiro_queda', 'Queda e técnica de defesas', 110, true),
    ('position', 'goleiro', 'monthly_goleiro_tomada', 'Tomada de decisão em saídas', 120, true),

    ('position', 'zagueiro', 'monthly_zagueiro_marcacao', 'Marcação e duelos 1x1', 10, true),
    ('position', 'zagueiro', 'monthly_zagueiro_jogo_aereo', 'Jogo aéreo (defesa)', 20, true),
    ('position', 'zagueiro', 'monthly_zagueiro_antecipacao', 'Antecipação e interceptação', 30, true),
    ('position', 'zagueiro', 'monthly_zagueiro_cobertura', 'Cobertura e proteção da área', 40, true),
    ('position', 'zagueiro', 'monthly_zagueiro_saida_bola', 'Saída de bola (passe/lançamento)', 50, true),
    ('position', 'zagueiro', 'monthly_zagueiro_linha', 'Sincronização da linha defensiva', 60, true),
    ('position', 'zagueiro', 'monthly_zagueiro_transicao', 'Transição defensiva', 70, true),
    ('position', 'zagueiro', 'monthly_zagueiro_comunicacao', 'Comunicação e liderança', 80, true),
    ('position', 'zagueiro', 'monthly_zagueiro_bote', 'Tempo de bote (sem falta)', 90, true),
    ('position', 'zagueiro', 'monthly_zagueiro_concentracao', 'Concentração e tomada de decisão', 100, true),
    ('position', 'zagueiro', 'monthly_zagueiro_protecao_bola', 'Proteção de bola e saída sob pressão', 110, true),
    ('position', 'zagueiro', 'monthly_zagueiro_intensidade', 'Intensidade e competitividade', 120, true),

    ('position', 'lateral', 'monthly_lateral_1x1_def', '1x1 defensivo e desarme', 10, true),
    ('position', 'lateral', 'monthly_lateral_recomposicao', 'Recomposição e transição', 20, true),
    ('position', 'lateral', 'monthly_lateral_apoio', 'Apoio ofensivo e amplitude', 30, true),
    ('position', 'lateral', 'monthly_lateral_cruzamento', 'Cruzamento e passe final', 40, true),
    ('position', 'lateral', 'monthly_lateral_leitura', 'Leitura de jogo e interceptação', 50, true),
    ('position', 'lateral', 'monthly_lateral_cobertura', 'Cobertura interna', 60, true),
    ('position', 'lateral', 'monthly_lateral_pressao', 'Pressão no portador', 70, true),
    ('position', 'lateral', 'monthly_lateral_dominio', 'Domínio/passe em velocidade', 80, true),
    ('position', 'lateral', 'monthly_lateral_tatica', 'Entender momento de subir/segurar', 90, true),
    ('position', 'lateral', 'monthly_lateral_duelos', 'Duelos no corredor', 100, true),
    ('position', 'lateral', 'monthly_lateral_resistencia', 'Resistência e repetição de sprints', 110, true),
    ('position', 'lateral', 'monthly_lateral_concentracao', 'Concentração e trocas de marcação', 120, true),

    ('position', 'volante', 'monthly_volante_protecao', 'Proteção da frente da zaga', 10, true),
    ('position', 'volante', 'monthly_volante_recuperacao', 'Recuperação e desarme', 20, true),
    ('position', 'volante', 'monthly_volante_marca_linhas', 'Marcar linhas e fechar espaços', 30, true),
    ('position', 'volante', 'monthly_volante_saida_bola', 'Saída de bola (passe/virada)', 40, true),
    ('position', 'volante', 'monthly_volante_tomada', 'Tomada de decisão sob pressão', 50, true),
    ('position', 'volante', 'monthly_volante_cobertura', 'Coberturas e dobras', 60, true),
    ('position', 'volante', 'monthly_volante_transicao', 'Transição (ganha/perde)', 70, true),
    ('position', 'volante', 'monthly_volante_organizacao', 'Organização do meio-campo', 80, true),
    ('position', 'volante', 'monthly_volante_comunicacao', 'Comunicação e liderança', 90, true),
    ('position', 'volante', 'monthly_volante_duelos', 'Duelos e intensidade', 100, true),
    ('position', 'volante', 'monthly_volante_leitura', 'Leitura de jogo e antecipação', 110, true),
    ('position', 'volante', 'monthly_volante_disciplina', 'Disciplina tática', 120, true),

    ('position', 'meia', 'monthly_meia_criacao', 'Criação (último passe e visão)', 10, true),
    ('position', 'meia', 'monthly_meia_controle', 'Controle orientado e giro', 20, true),
    ('position', 'meia', 'monthly_meia_passe', 'Passe sob pressão', 30, true),
    ('position', 'meia', 'monthly_meia_drible', 'Drible em espaço curto', 40, true),
    ('position', 'meia', 'monthly_meia_finalizacao', 'Finalização de média distância', 50, true),
    ('position', 'meia', 'monthly_meia_entre_linhas', 'Movimento entre linhas', 60, true),
    ('position', 'meia', 'monthly_meia_decisao', 'Decisão (acelerar ou pausar)', 70, true),
    ('position', 'meia', 'monthly_meia_pressao', 'Pressão pós-perda', 80, true),
    ('position', 'meia', 'monthly_meia_compactacao', 'Recomposição e compactação', 90, true),
    ('position', 'meia', 'monthly_meia_leitura', 'Leitura do jogo (linhas de passe)', 100, true),
    ('position', 'meia', 'monthly_meia_comunicacao', 'Comunicação e liderança', 110, true),
    ('position', 'meia', 'monthly_meia_constancia', 'Constância e controle emocional', 120, true),

    ('position', 'ponta', 'monthly_ponta_1x1', '1x1 ofensivo (drible e quebra)', 10, true),
    ('position', 'ponta', 'monthly_ponta_velocidade', 'Velocidade com bola e sem bola', 20, true),
    ('position', 'ponta', 'monthly_ponta_cruzamento', 'Cruzamento e passe final', 30, true),
    ('position', 'ponta', 'monthly_ponta_finalizacao', 'Finalização (corte e chute)', 40, true),
    ('position', 'ponta', 'monthly_ponta_movimento', 'Movimento de profundidade', 50, true),
    ('position', 'ponta', 'monthly_ponta_dominio', 'Domínio e condução na linha', 60, true),
    ('position', 'ponta', 'monthly_ponta_pressao', 'Pressão e recomposição', 70, true),
    ('position', 'ponta', 'monthly_ponta_decisao', 'Decisão no 1x1 (drible vs passe)', 80, true),
    ('position', 'ponta', 'monthly_ponta_sem_bola', 'Movimento sem bola (apoio e ruptura)', 90, true),
    ('position', 'ponta', 'monthly_ponta_duelos', 'Duelos e competitividade', 100, true),
    ('position', 'ponta', 'monthly_ponta_coragem', 'Coragem e responsabilidade', 110, true),
    ('position', 'ponta', 'monthly_ponta_constancia', 'Constância no mês', 120, true),

    ('position', 'atacante', 'monthly_atacante_finalizacao', 'Finalização (qualidade e escolha)', 10, true),
    ('position', 'atacante', 'monthly_atacante_movimento_area', 'Movimento na área e desmarque', 20, true),
    ('position', 'atacante', 'monthly_atacante_pivo', 'Apoio/pivô (parede e retenção)', 30, true),
    ('position', 'atacante', 'monthly_atacante_profundidade', 'Ataque à profundidade', 40, true),
    ('position', 'atacante', 'monthly_atacante_1x1', '1x1 em zona de finalização', 50, true),
    ('position', 'atacante', 'monthly_atacante_pressao', 'Pressão na saída adversária', 60, true),
    ('position', 'atacante', 'monthly_atacante_decisao', 'Decisão no último terço', 70, true),
    ('position', 'atacante', 'monthly_atacante_sem_bola', 'Movimento sem bola e leitura de cruzamentos', 80, true),
    ('position', 'atacante', 'monthly_atacante_duelos', 'Duelos e proteção de bola', 90, true),
    ('position', 'atacante', 'monthly_atacante_coragem', 'Coragem e mentalidade de gol', 100, true),
    ('position', 'atacante', 'monthly_atacante_temperamento', 'Controle emocional', 110, true),
    ('position', 'atacante', 'monthly_atacante_constancia', 'Constância e competitividade', 120, true)
) as v(kind, position, key, prompt, sort_order, active)
where s.is_active = true
on conflict (season_id, kind, position, key) do nothing;
